include_recipe "php"
package "php5-mysql"
package "php5-mcrypt"
package "php5-memcached"
package "pkg-config"
package "php5-xsl"
package "php-xml-rpc"
package "php5-gmp"
package "php5-curl"
package "imagemagick"
package "php5-imagick"
package "php5-json"
package 'libpspell-dev'
package 'php5-pspell'
package 'aspell-en'
package "php5-enchant"
package "php5-ffmpeg"
